# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: detect-package-manager
        run: |
          if [ -f "yarn.lock" ]; then echo "manager=yarn;command=install;runner=yarn" >> $GITHUB_OUTPUT; fi
          if [ -f "package.json" ]; then echo "manager=npm;command=ci;runner=npx --no-install" >> $GITHUB_OUTPUT; fi
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: actions/configure-pages@v5
        with:
          static_site_generator: next
      - run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
      - run: ${{ steps.detect-package-manager.outputs.runner }} next build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: out

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4